# stub file for fastapi_csrf_protect to satisfy Pyright
from typing import Any, Callable

class CsrfProtect:
    @classmethod
    def load_config(cls, func: Callable[..., Any]) -> Callable[..., Any]: ...

    def __init__(self) -> None: ...
    def validate_csrf_in_cookies(self, request: Any) -> None: ...
    def set_csrf_cookie(self, response: Any) -> None: ...

class CsrfProtectError(Exception): ... 