[build]
  base = "frontend"
  command = """
    pnpm install &&
    pnpm run build
  """
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  PNPM_VERSION = "10.12.1"
  GIT_TERMINAL_PROMPT = "0"
  GIT_SSH_COMMAND = "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# Python 패키지 설치를 위한 환경 설정
[build.processing]
  skip_processing = false 