[build]
  base = "frontend"
  command = "python -m ensurepip && pip install --upgrade pip && cd .. && pip install -r requirements.txt && cd frontend && pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.8"
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  PNPM_VERSION = "10.12.1"

# Python 패키지 설치를 위한 환경 설정
[build.processing]
  skip_processing = false 