# Loop AI - GigaChad Edition Render Blueprint
# ==============================================================================
# Infrastructure as Code for fully-automated, optimized deployments on Render.
# ------------------------------------------------------------------------------

services:
  - type: web
    name: loop-ai-backend
    env: docker
    port: 8080
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
      - key: KEY_TAG
      - key: NEUTRINO_USER_ID
      - key: KEY
      - key: NEUTRINO_API_KEY
      - key: REDIS_URL
        value: ""
    healthCheckPath: "/api/health"
    autoDeploy: true
    branch: main

  # -------------------------------------
  # 2. Frontend Web App (Next.js)
  # -------------------------------------
  - type: static
    name: loop-ai-frontend
    plan: free
    buildCommand: |
      pnpm install -g pnpm@9.1.0
      cd frontend
      pnpm install
      pnpm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: loop-ai-backend
          property: url

    # 정적 파일 배포 경로 (rootDirectory 기준)
    publishPath: "out"

    # 모든 경로를 index.html로 리다이렉트하여 Next.js 라우팅 지원
    rewriteRules:
      - source: /_next/static/*
        destination: /_next/static/*
      - source: /favicon.ico
        destination: /favicon.ico
      - source: /*
        destination: /index.html 