# Loop AI - GigaChad Edition Render Blueprint
# ==============================================================================
# Infrastructure as Code for fully-automated, optimized deployments on Render.
# ------------------------------------------------------------------------------

services:
  # -------------------------------------
  # 1. Backend API Server (FastAPI)
  # -------------------------------------
  - type: web
    name: loop-ai-backend
    env: python
    plan: free
    healthCheckPath: /api/health
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn src.inference.api.server:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY_LOOP
      - key: TAVILY_API_KEY
        fromSecret: TAVILY_API_KEY_LOOP
      - key: GOOGLE_API_KEY
        fromSecret: GOOGLE_API_KEY_LOOP
      - key: GOOGLE_CSE_ID
        fromSecret: GOOGLE_CSE_ID_LOOP

  # -------------------------------------
  # 2. Frontend Web App (Next.js)
  # -------------------------------------
  - type: static
    name: loop-ai-frontend
    plan: free
    buildCommand: |
      pnpm install -g pnpm@9.1.0
      cd frontend
      pnpm install
      pnpm run build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: loop-ai-backend
          property: url

    # 정적 파일 배포 경로 (rootDirectory 기준)
    publishPath: "out"

    # 모든 경로를 index.html로 리다이렉트하여 Next.js 라우팅 지원
    rewriteRules:
      - source: /_next/static/*
        destination: /_next/static/*
      - source: /favicon.ico
        destination: /favicon.ico
      - source: /*
        destination: /index.html 